CREATE TABLE COLLEGE (
ID INT PRIMARY KEY,
STUDENT_NAME VARCHAR(50),
CITY VARCHAR(50),
AGE INT,
MARKS INT,
GRADE VARCHAR(20)
);

INSERT INTO COLLEGE VALUES (1, 'AMAN', 'PUNE', 20, '77', 'B');
INSERT INTO COLLEGE VALUES (2, 'PRIYA', 'MUMBAI', 21, '95', 'AA');
INSERT INTO COLLEGE VALUES (3, 'NIKITA', 'DELHI', 21, '97', 'C');
INSERT INTO COLLEGE VALUES (4, 'YUVRAJ', 'MUMBAI', 24, '80', 'B');
INSERT INTO COLLEGE VALUES (5, 'MANIL', 'PUNE', 25, '89', 'A');
INSERT INTO COLLEGE VALUES (6, 'TEJAS', 'PUNE', 24, '90', 'A');
INSERT INTO COLLEGE VALUES (7, 'BALAJI', 'DELHI', 27, '60', 'D');

ALTER TABLE COLLEGE ADD COLUMN EMAIL VARCHAR(100);

UPDATE COLLEGE SET EMAIL = 'AMAN@GMAIL.COM' WHERE STUDENT_NAME = 'AMAN';
UPDATE COLLEGE SET EMAIL = 'PRIYA@GMAIL.COM' WHERE STUDENT_NAME = 'PRIYA';
UPDATE COLLEGE SET EMAIL = 'NIKITA@GMAIL.COM' WHERE STUDENT_NAME = 'NIKITA';
UPDATE COLLEGE SET EMAIL = 'YUVRAJ@GMAIL.COM' WHERE STUDENT_NAME = 'YUVRAJ';
UPDATE COLLEGE SET EMAIL = 'MANIL@GMAIL.COM' WHERE STUDENT_NAME = 'MANIL';
UPDATE COLLEGE SET EMAIL = 'TEJAS@GMAIL.COM' WHERE STUDENT_NAME = 'TEJAS';
UPDATE COLLEGE SET EMAIL = 'BALAJI@GMAIL.COM' WHERE STUDENT_NAME = 'BALAJI';

UPDATE COLLEGE SET MARKS = '97' WHERE STUDENT_NAME = 'NIKITA';

SELECT * FROM COLLEGE;
SELECT STUDENT_NAME, CITY FROM COLLEGE;
SELECT STUDENT_NAME, CITY, MARKS FROM COLLEGE WHERE MARKS >= 80;
SELECT STUDENT_NAME, CITY, MARKS FROM COLLEGE WHERE MARKS BETWEEN 60 AND 80;
SELECT STUDENT_NAME, CITY, MARKS FROM COLLEGE WHERE MARKS <= 60;

ALTER TABLE COLLEGE ADD COLUMN EXAM_RESULT VARCHAR(20);

UPDATE COLLEGE SET EXAM_RESULT = 'PASS' WHERE MARKS > 61;
UPDATE COLLEGE SET EXAM_RESULT = 'FAIL' WHERE MARKS <= 60;

SELECT STUDENT_NAME, CITY, MARKS FROM COLLEGE ORDER BY MARKS DESC;

SELECT CITY, COUNT(CITY) FROM COLLEGE GROUP BY CITY HAVING MAX(MARKS) > 90;
SELECT CITY, AVG(MARKS) FROM COLLEGE GROUP BY CITY ORDER BY AVG(MARKS) ASC;

SELECT CITY, COUNT(CITY) FROM COLLEGE GROUP BY CITY;

SELECT CITY, AVG(MARKS) FROM COLLEGE GROUP BY CITY;

SELECT CITY, AVG(MARKS) FROM COLLEGE GROUP BY CITY ORDER BY AVG(MARKS) DESC;

SELECT CITY, COUNT(ID) FROM COLLEGE GROUP BY CITY HAVING MAX(MARKS) > 90;

SELECT * FROM COLLEGE WHERE MARKS = '97';
UPDATE COLLEGE SET GRADE = 'AA' WHERE MARKS > '91';

SELECT GRADE, COUNT(GRADE) FROM COLLEGE GROUP BY GRADE;

SELECT EXAM_RESULT, COUNT(EXAM_RESULT) FROM COLLEGE GROUP BY EXAM_RESULT;

SELECT STUDENT_NAME, CITY, MARKS, GRADE FROM COLLEGE WHERE MARKS BETWEEN 80 AND 100 AND CITY = 'MUMBAI';
SELECT STUDENT_NAME, CITY, MARKS, GRADE FROM COLLEGE WHERE MARKS BETWEEN 80 AND 100 AND CITY = 'PUNE';

SELECT STUDENT_NAME, MARKS, GRADE, EXAM_RESULT FROM COLLEGE WHERE NOT EXAM_RESULT = 'PASS';

SELECT DISTINCT STUDENT_NAME, CITY, AGE, MARKS, GRADE, EXAM_RESULT FROM COLLEGE; 

SELECT STUDENT_NAME FROM COLLEGE WHERE STUDENT_NAME LIKE 'A%';
SELECT STUDENT_NAME FROM COLLEGE WHERE STUDENT_NAME LIKE '%A';
SELECT STUDENT_NAME FROM COLLEGE WHERE STUDENT_NAME LIKE '%A%';

SELECT STUDENT_NAME, COUNT(STUDENT_NAME) FROM COLLEGE WHERE STUDENT_NAME LIKE 'A%' GROUP BY STUDENT_NAME;
SELECT STUDENT_NAME, COUNT(STUDENT_NAME) FROM COLLEGE WHERE STUDENT_NAME LIKE '%A' GROUP BY STUDENT_NAME;
SELECT STUDENT_NAME, COUNT(STUDENT_NAME) FROM COLLEGE WHERE STUDENT_NAME LIKE '%A%' GROUP BY STUDENT_NAME;

SELECT * FROM COLLEGE WHERE ID IN(3,4,5);
SELECT * FROM COLLEGE WHERE EMAIL IS NULL;

SELECT STUDENT_NAME, MARKS FROM COLLEGE;
SELECT MARKS, AVG(MARKS) FROM COLLEGE GROUP BY MARKS ORDER BY MARKS ASC;















